### ISSUE TITLE
Checklist - ler antes de entregar a tarefa

### ISSUE THREAD

**Issue by Schneiderella** [pedrin-pedrada/linkedlists#1]
# Checklist:

## O código contempla as seguintes operações básicas:
Marque as operações contempladas e testadas abaixo.
- [ ] Inclui emissor na lista de emissores
- [ ] Remove emissor da lista de emissores
- [ ] Consulta emissores: escreve na tela os emissores cadastrados
- [ ] Inclui receptor na lista de receptores
- [ ] Remove receptor da lista de receptores: quando o receptor é removido, sua fila de mensagens também é removida
- [ ] Consulta receptores: escreve na tela os receptores cadastrados
- [ ] Envia mensagem: um receptor cadastrado escreve a mensagem, e define quais são os receptores (pelo menos um receptor). A mensagem é enfileirada na fila de cada receptor.
- [ ] Retira mensagem: um receptor cadastrado desenfileira uma mensagem (apresenta mensagem de erro se a fila está vazia)
- [ ] Consulta fila de mensagens: exibe a fila de mensagens de um receptor
- [ ] Outras operações (a critério), como: exibe receptores com fila vazia, exibe receptores com mais mensagens na fila, exibe total de mensagens enviadas por um emissor, exibe total de mensagens recebidas por um receptor.

## Representação:
- [ ] Usa listas encadeadas (simples ou duplas).
- [ ] Cada nodo da lista de emissores deve conter: número de identificação (inteiro), nome (string).
- [ ] Cada nodo da lista de receptores deve conter: número de identificação (inteiro), nome (string)
- [ ] Cada fila de mensagens deve conter: identificação do receptor (inteiro), e a fila de mensagens.
- [ ] Cada nodo da fila de mensagens deve conter: a identificação do emissor (inteiro), e a mensagem (texto).
É possível acrescentar outras informações nos nodos/listas se necessário.

## Fazer upload do trabalho na tarefa correspondente no AVA do trabalho com:
- [ ] Código-fonte da implementação,.
- [ ] Explicação textual (ou figura) sobre a estrutura de dados utilizada (como é cada lista, simples ou dupla; se foram incluídas informações ou estruturas adicionais dizer quais são.
